services:
  cleanrobust.api:
    image: ${DOCKER_REGISTRY-}cleanrobustapi
    build:
      context: ./CleanRobust.API
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
     - "8081:8081"
    depends_on:
     - sqlserver
    networks:
     - cleanrobust-network
    restart: on-failure

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
     SA_PASSWORD: "123456@#Az"
     ACCEPT_EULA: "Y"
    ports:
     - "1443:1443"
    volumes:
     - sqlvolume:/var/opt/mssql
    networks:
     - cleanrobust-network
networks:
   cleanrobust-network:

volumes: 
  sqlvolume:

    
